import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center min-h-[80px] p-8 sm:p-8">
        <Link href="/" className="flex items-center">
            <span className="text-lg font-semibold">Mutual Aid Live</span>
          </Link>

          {/* Center: Navbar Text */}
          <div className="text-center">
            <h1 className="text-lg font-semibold">CA Wildfires</h1>
          </div>

          {/* Right: Hamburger Menu */}
          <Link href="/account" className="flex items-center">
          <span className="text-lg font-semibold">+</span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
